### ISSUE TITLE
Tumor Normal paired variant calling

### ISSUE THREAD

**Issue by phoebee-h** [EtieM/outLyzer#1]
Hello Etienne,
I'm a novice in Bioinformatics, so I really need a guide or tutorial to use your program in case I mess up.
If I had a paired Tumor/Normal fastq file, what basic command should be used in this case? I've already had them go through the pre-process like marking duplicate...etc. 
I don't have a certain bed file but I have a vcf file for reporting the mutations. 

Thank you. :)

**Comment by EtieM** [comment]
Hello Phoebee,

outLyzer doesn't supports paired Tumor/normal files (this is why it was created, when normal file is not available!), you just have to launch it with tumor file (which must be a BAM file).
But you have to provide a bed file for analysis. Where this data come from ? (Genome, Exome, targeted sequencing?)

If you have no bed file available, you can create one by using UCSC table Browser (https://genome.ucsc.edu/cgi-bin/hgTables) and provide genes to be analyzed.

Then try this command:

`python outLyzer.py calling -ref genome.fa -bed regionsToAnalyze.bed -bam tumorFile.bam -output  outputDirectory`

Let me know if it works.
