### ISSUE TITLE
Process killed for whole genome analysis 

### ISSUE THREAD

**Issue by dollinad** [EtieM/outLyzer#2]
Hi, 

I am using outLyzer to call variants in some tumor samples (hg38). outLyzer worked perfectly when I tested it on a single chromosome, but gets killed when I test the whole genome. 

```
The command I am running is: 
path_to_python2.7.16 outLyzer.py calling 
-bam tumor_bam 
-ref hg38_no_alt.fa 
-bed tumor_bam.bed 
-samtools path_to_samtools-0.1.19
 -pythonPath path_to_python-2.7.16
 -output path_to_output_directory 
```
The error generated is:
```
starting outLyzer Calling Process
Killed
```

Any help is appreciated!

Thanks, 
Dollina

**Comment by EtieM** [comment]
Hi Dollina,

Thanks for your feedback. What is the size of your sample? Targeted sequencing (number of genes), exome, whole genome?
I have rarely tested outLyzer on really big samples, but in this case, i think you have to divide much more your bed file with the "cut" parameter. In fact if you let this parameter by default (3), the bed is first divided in 3 equal parts. for each part, a pileup is generated and loaded directly in memory. This default parameter works fine for relatively small samples (samples with panels of 500 genes work too). But for big samples like exomes for example, outlyzer will try to load one third of an exome pileup in memory, which is probably too much! ==> Crash
So try to re-run it by adding the parameter "-cut 300" and if you have a multi-core computer '-core 2' or more than 2 if you have a lot of cores.

If your not in that case or if it doesn't work, check if your reference genome for one chromosome and your whole genome are formated the same way.

finally if nothing works, tell me and we'll continue investigations!

Etienne

**Comment by dollinad** [comment]
Hi Etienne, 

Thanks for the quick reply.

I am trying to call variants in whole genomes. I have updated the command and it still crashes. 

```
path_to_python-2.7.16 outLyzer.py calling
 -bam tumor_bam 
-ref hg38_no_alt.fa 
-bed tumor_bam.bed 
-cut 300 
-core 5 
-samtools path_to_samtools-0.1.19
 -pythonPath path_to_python-2.7.16
 -output path_to_output_directory
-verbose 1
```

I have also checked the formatting of my reference and genome (both are Hg38).
 
Thanks, 
Dollina

**Comment by EtieM** [comment]
Your machine seems still overloaded. For exomes, cutting bed in 300 parts worked. Maybe for genomes you have to cut it in many more parts (10 000, 100 000).
But that's weird if it worked for one chromosome.
Can you send me an exemple of your chromosome bed file and genome bed file (or at least a few lines of it)?

**Comment by dollinad** [comment]
Hi, 

I tried cutting the bed file into 10 000 and 100 000 parts and I get the same result. 

Here are a few lines from the bed file I provide:
```
chr1    9991    10134   HISEQX1_44:1:2201:2717:43818/2  2       +
chr1    9991    10134   HISEQX1_44:1:1207:9851:25271/2  1       +
chr1    9992    10141   HISEQX1_44:2:1109:21785:44890/2 2       +
chr1    9992    10141   HISEQX1_44:1:2113:14519:63665/2 2       +
chr1    9992    10133   HISEQX1_44:2:1116:24200:46156/2 2       +
chr1    9992    10119   HISEQX1_44:1:1115:4553:68377/1  2       +
chr1    9992    10142   HISEQX1_44:2:2104:16488:62189/1 2       +
chr1    9992    10126   HISEQX1_44:1:1106:18071:19821/1 2       +
chr1    9993    10143   HISEQX1_44:1:1103:5578:66074/2  1       +
chr1    9993    10144   HISEQX1_44:1:2109:32471:7462/1  2       +
chr1    9994    10144   HISEQX1_44:2:1216:5457:5036/1   1       +
chr1    9994    10144   HISEQX1_44:1:1105:22465:69695/1 1       +
chr1    9994    10144   HISEQX1_44:2:1208:10724:43062/1 2       +
chr1    9994    10144   HISEQX1_44:2:1216:2940:6970/1   2       +

```
Thanks, 
Dollina

**Comment by EtieM** [comment]
The construction of your bed is strange. Even on this small exemple, you have a lot of overlapping regions and each region is relatively small. I thinks this bed describes the position of each probe of your capture. 
Which sample prep kit and probe kit do you use for capturing and dequencing your samples? The manufacturer should also provide a bed file summerizing captured regions.
If you don't have another bed available, try this on your bed:
https://bedtools.readthedocs.io/en/latest/content/tools/merge.html
Bedtools will merge all overlapping regions and give you a merged bed file, with wich you can run outLyzer again.

**Comment by EtieM** [comment]
When i try it with your example:
bedtools2-2.25.0/bin/bedtools merge -i testBed.bed

It returns:
chr1	9991	10144

**Comment by dollinad** [comment]
Hello, 

Thank you, That helped

Dollina
