### ISSUE TITLE
About the Output_vcf Result question

### ISSUE THREAD

**Issue by jsonProgram** [EtieM/outLyzer#4]
hi, EtieM:
I use the outLyzer with default parameter.

<<running code 

outLyzer/outLyzer.py calling -bed my.bed -bam my.bam -out /Path/to/result -core 10 -pythonPath /usr/bin/python2.7

<<end

I got the MSS value in the VCF which i could not sure what that meaning. 

For example:
S5d3: 
Somatic Variants Number  is 5 ?
Deletion Number is 3 ?
Is it right ?

M17d1:
Repeat Motif Number is 17 ?
Deletion Number is 1?

Thank for help!
Json

**Comment by EtieM** [comment]
hi Json,

MSS values are a help to interpret the likelihood of a variation, based on the fact that false positive are more often generated around repetitive regions (alignment issue or other...).
So, for example:
-S5d3: you have a stretch (S) of five identical nucleotides at a distance of 3 nucleotides from your variation.
-M17d1: you have of pattern (M, for motif) of 17 nucleotides of length just next to your variation (distance of 1 nucleotide from the variation).

Tell me if there are other questions!

**Comment by jsonProgram** [comment]
Hi EtieM,

Thank you very much for your reply!
You solved my doubts.
