### ISSUE TITLE
Question : How can I get the HSM file ?

### ISSUE THREAD

**Issue by jsonProgram** [EtieM/outLyzer#5]
hi EtieM,

I check the HSM file from your files.

I have no idea about how to create HSM file which can use in my bam file.

Any suggestions?

Json

**Comment by EtieM** [comment]
Hi jsomProgram,

This option is designed to check the sensitivity of the analysis on known specific positions (ex: mutational hotspots of KRAS or EFGR genes).
The file must therefore be created as a bed file, indicating genomic positions on which you want to have an evaluation of sensitivity (ex: chr1   123456   123457).
Then you add the parameter
`-HSM yourBedFileForPositions.bed` 
When you run outLyzer.

This option can be usefull when you want to ensure that your analysis meets sensitivity quality requirements (for diagnostic use for example)

I hope this answer your question

EtieM

**Comment by jsonProgram** [comment]
Hi Etienne,

Thank you for your very prompt reply and your patient.



Json

**Comment by jsonProgram** [comment]
Stay safe！
