### ISSUE TITLE
Question about the FRcor option

### ISSUE THREAD

**Issue by HugoMananet** [EtieM/outLyzer#6]
Hi EtieM,

Could you explain how the -FRcor parameter works ? 

- Is it applied only when added to the Outlyzer command ? 

- What happens if the proportion of reads are predominantly Forward or Reverse with and without this parameter ?

Thanks.

**Comment by EtieM** [comment]
Hello,
Indeed it is applied only when added in the command, it's not applied by default.
For exemple If you have a mutation supported by 80% with Forward reads ( and so 20% of reverse reads) with "-bal" option by default at 0.3 = 30% ==> the proportion of reverse mutated reads is below the proportion allowed by bal option, the mutation is discard.
Now if you add the FRcor option, outlyzer will count the proportion of Wild-Type reads too. If the proportion is unbalanced too for WT reads, it will apply a correction to the mutated ratio.
Ex: 80% of mutated reads in forward, but also 80% of WT reads in forward ==> correction applied ==> 50% of mutated reads in forward after correction ==> mutation is not discard anymore.

**Comment by HugoMananet** [comment]
Hi again,

Thanks a lot for your explanation.

Sorry for the late response,
Hugo
